name: deploy
run-name: create build and deploy
on:
  release:
    types: [created]
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.ACC3SS_T0K3N }}

      - name: install dependencies
        run: npm install

      - name: build the project
        run: npm run build

      - name: deploy
        run: |
          export ${{ secrets.NPM_ACC3SS_T0K3N }}
          npm publish
