name: release
run-name: create release/${{github.ref_name}}
on:
  push:
    tags:
      - v*.*.*
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.ACC3SS_T0K3N }}

      - name: creation
        env:
          GH_TOKEN: ${{ secrets.ACC3SS_T0K3N }}
        run: |
          gh release create ${{ github.ref_name }}
